name: kotonohack
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  url_launcher: ^6.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.4
  twitter_api_v2: ^2.9.0
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/1024.png"
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/1024.png'
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.4
flutter_native_splash:
  image: "assets/images/akane_aoi3.png"
  color: "#e6effe"
  android: true
  ios: true

flutter:

  fonts:
    - family: Patrick_Hand
      fonts:
        - asset: assets/fonts/Patrick_Hand/PatrickHand-Regular.ttf
          weight: 100
        - asset: assets/fonts/Patrick_Hand/PatrickHand-Regular.ttf
          weight: 200
        - asset: assets/fonts/Patrick_Hand/PatrickHand-Regular.ttf
          weight: 300
        - asset: assets/fonts/Patrick_Hand/PatrickHand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Patrick_Hand/PatrickHand-Regular.ttf
          weight: 500
        - asset: assets/fonts/Patrick_Hand/PatrickHand-Regular.ttf
          weight: 600
  uses-material-design: true
  assets:
    - images/twitter.png
    - assets/images/SD2姉妹.png
    - assets/images/SD6おんぶ姉妹.png
    - assets/images/SD4座り姉妹.png
    - assets/images/SD5膝枕姉妹.png
    - assets/images/SD2姉妹.png
